import { EnforcementResult } from './policy-runner';

export class MarkdownReporter {
  public static generateCiReport(result: EnforcementResult): string {
    const statusIcon = result.passed ? '✅' : '❌';
    const statusText = result.passed ? 'PASSED' : 'FAILED';
    
    let markdown = `## ${statusIcon} Security Policy Enforcement: ${statusText}\n\n`;
    markdown += `**Version:** ${result.effectivePolicy.version} | **Scope:** ${result.effectivePolicy.scope}\n\n`;

    if (result.rejections.length > 0) {
      markdown += `### 🛑 Gates Failed\n`;
      for (const rejection of result.rejections) {
        markdown += `- **${rejection}**\n`;
      }
      markdown += `\n`;
    }

    markdown += `### 🛡️ Enforced Findings (${result.enforcedFindings.length})\n`;
    if (result.enforcedFindings.length === 0) {
      markdown += `*No policy violations detected.*\n`;
    } else {
      markdown += `| Rule ID | File | Line |\n`;
      markdown += `| :--- | :--- | :--- |\n`;
      
      for (const finding of result.enforcedFindings) {
        const safePath = this.sanitizePath(finding.file);
        markdown += `| \`${finding.ruleId}\` | \`${safePath}\` | ${finding.line} |\n`;
      }
    }

    markdown += `\n---\n*Report generated by @chainproof/cli*`;
    return markdown;
  }

  private static sanitizePath(rawPath: string): string {
    const workspaceIndicator = 'StellarChainproofs/';
    const index = rawPath.indexOf(workspaceIndicator);
    if (index !== -1) {
      return rawPath.substring(index + workspaceIndicator.length);
    }
    const parts = rawPath.split(/[/\\]/);
    return parts.length > 3 ? '.../' + parts.slice(-3).join('/') : rawPath;
  }
}
